### ISSUE TITLE
[Feature] update readme on how a user can add their own languages as part of language detection 

### ISSUE THREAD

**Issue by Bytes-Explorer** [data-prep-kit/data-prep-kit#166]
### Search before asking

- [X] I searched the [issues](https://github.com/IBM/data-prep-lab/issues) and found no similar issues.

### Component

Tools/ingest2parquet

### Feature

Enhancement in readme to help the user to add their own languages to https://github.com/IBM/data-prep-kit/blob/dev/tools/ingest2parquet/src/utils/lang_extensions.json

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

**Comment by shahrokhDaijavad** [comment]
@Bytes-Explorer Adding a sentence or two about adding to the appropriate json file should be done to this README file: transforms/code/code2parquet/python/README.md, since we will be deprecating the ingest2parquet tool soon. @daw3rd Since you are modifying the Readme files today, can you please add an appropriate sentence, hyperlinking to the the file that needs to be changed, i.e., transforms/code/code2parquet/python/test-data/languages/lang_extensions.json?

**Comment by Bytes-Explorer** [comment]
has this been done @shahrokhDaijavad ?

**Comment by shahrokhDaijavad** [comment]
Yes, @Bytes-Explorer
